apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: demo
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: nightfury1204/reverse-proxy-demo:canary
          imagePullPolicy: Always
          args:
            - "--reverse-proxy-url=http://m3query.demo.svc:7201"
            - "--port=8080"
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: demo
spec:
  selector:
    app: reverse-proxy
  ports:
    - port: 8080
      protocol: TCP
      name: http
  type: ClusterIP
